export default {
    SET_RTL: "SET_RTL",
    SET_LOGIN: 'SET_LOGIN',
    SET_USER: "SET_USER",
    SET_LOGOUT: 'SET_LOGOUT',
    RESET_PASSWORD: 'RESET_PASSWORD',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
}