export default {
    logo: require('@images/logo.png'), 
    welcome: require('@images/welcome.png'),
    logo_light: require('@images/logo_light.png'),
    logo_dark: require('@images/logo_dark.png'),
    avatar: require('@images/avatar.png'),
    slide1: require('@images/slide01.png'),
    slide2: require('@images/slide03.png'),
    slide3: require('@images/slide04.png'),
    slide4: require('@images/slide06.png'),
    slide5: require('@images/slide07.png'),
    slide6: require('@images/slide08.png'),
    slide7: require('@images/slide09.png'),
    slide8: require('@images/slide10.png'),
    slide9: require('@images/slide17.png'),
    slide10: require('@images/slide27.png'),
    slide11: require('@images/slider/slide81.png'),
    
    bg_dark: require('@images/bg.jpg'), 
    bg_light: require('@images/bg_light.jpg'), 
    workouts: require('@images/workouts.png'),
    exercises: require('@images/exercises.png'),
    diets: require('@images/diets.png'),
    blog: require('@images/blog.png'),
    quotes: require('@images/quotes.png'),
    profile: require('@images/profile.png'),
    settings: require('@images/settings.png'),
    signout: require('@images/signout.png')
}