export default {
    ST300: "Get Started",
    ST301: "Sign In",    
    ST302: "Sign Up",
    ST303: "Email / National ID",
    ST304: "Password",
    ST305: "Enter",
    ST306: "Log In",
    ST307: "Register",
    ST308: "Forgot Password",
    ST309: "Create new account",
    //Login Message
    ST310: "Please enter email / national id",
    ST311: "Please enter password",
    ST312: "Please enter login info",
    ST313: "Warning",
    ST314: "Error",
    ST315: "Login Failed",
    ST316: "Success",
    ST317: "Login Success",
    ST318: "Reset password Success",
    ST319: "Reset password Failed",
    ST320: "Please enter email",
    //Signup Page
    ST321: "National ID",
    ST322: "Full Name",
    ST323: "Email",
    ST324: "Phone Number",
    ST325: "Birthday",
    ST326: "Privacy & Terms",
    //Signup Message
    ST327: "Please enter national id",
    ST328: "Please enter phone number",
    ST329: "Please select birthday",
    ST330: "Please enter register info",
    ST331: "Please enter name",
    ST332: "Register Success",
    ST333: "Register Failed",
    ST334: "Invalid Email",
    ST335: "Please enter email again",
    ST336: "Gender" 
};
